### ISSUE TITLE
[Feature req] Store availability about local cached or stored files in memory.

### ISSUE THREAD

**Issue by zidz** [rawler/bithorde#45] opened 2016-06-02 10:36 UTC
Store availability about local cached or linked files in memory, as an option.
When a node request availability of a file bithorded will now generate IO to check if the file is available on the file system.
It would be a good thing to read synchronous file per file with high timeout from file system during initial start of bithorded and store availability in memory this to not put fatal pressure on slow storage.
Nice to have configuration with be read pressure, lookup timeout and how often it should cyclic update available files.

**Comment by rawler** [comment] 2016-06-03 10:32
Duplicate of #31. Discussion continued there.

**Closed by rawler** 2016-06-03 10:32 UTC
